# Server
server.port=8080

# PostgreSQL - CHANGE PASSWORD TO YOURS
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudsec_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - auto creates all tables on first run
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.file.upload-dir=./uploads

# JWT
app.jwt.secret=CloudSecAuditingSystem2024SecretKeyForHS256AlgorithmMustBeLong
app.jwt.expiration-ms=86400000

# CORS - allow React frontend
app.cors.allowed-origins=http://localhost:3000
