package com.cloudsec.controller;

import com.cloudsec.entity.User;
import com.cloudsec.repository.UserRepository;
import com.cloudsec.security.JwtUtils;
import com.cloudsec.service.PkgService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import java.util.Map;

@RestController
@RequestMapping("/api/auth")
public class AuthController {

    @Autowired private AuthenticationManager authManager;
    @Autowired private UserRepository userRepo;
    @Autowired private PasswordEncoder encoder;
    @Autowired private JwtUtils jwtUtils;
    @Autowired private PkgService pkgService;

    @PostMapping("/register")
    public ResponseEntity<?> register(@RequestBody Map<String, String> body) {
        String username = body.get("username");
        String email    = body.get("email");
        String password = body.get("password");
        String roleStr  = body.getOrDefault("role", "USER");

        if (userRepo.existsByUsername(username))
            return ResponseEntity.badRequest().body(Map.of("message", "Username already taken"));
        if (userRepo.existsByEmail(email))
            return ResponseEntity.badRequest().body(Map.of("message", "Email already in use"));

        User.Role role;
        try { role = User.Role.valueOf(roleStr); }
        catch (Exception e) { role = User.Role.USER; }

        String identityHash = pkgService.generateIdentityHash(username, email);
        String publicKey    = pkgService.generatePublicKey(identityHash);

        User user = User.builder()
                .username(username).email(email)
                .password(encoder.encode(password))
                .role(role).identityHash(identityHash).publicKey(publicKey)
                .build();
        userRepo.save(user);
        return ResponseEntity.ok(Map.of("message", "User registered successfully! Identity key generated by PKG."));
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody Map<String, String> body) {
        Authentication auth = authManager.authenticate(
                new UsernamePasswordAuthenticationToken(body.get("username"), body.get("password")));
        SecurityContextHolder.getContext().setAuthentication(auth);
        String jwt = jwtUtils.generateToken(auth);
        UserDetails ud = (UserDetails) auth.getPrincipal();
        User user = userRepo.findByUsername(ud.getUsername()).orElseThrow();
        return ResponseEntity.ok(Map.of(
                "token",    jwt,
                "id",       user.getId(),
                "username", user.getUsername(),
                "email",    user.getEmail(),
                "role",     user.getRole().name()
        ));
    }
}
